title: "Rafal Masiarek"
url: "https://masiarek.pl"
baseurl: ""

description: "I am devops. Automation and configuration management tools are the foundation of my work"
github_repo: "https://github.com/rafalmasiarek/rafalmasiarek.github.io"

recaptcha_site_key: "6LfvSI4rAAAAABdOXvYNnDMZEzd_K57A94LlEghS"

# plugins
plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-assets

collections:
  vinyls:
    output: true
    permalink: /vinyls/:name/

nav:
  - title: Home
    url: /
  - title: Contact
    url: /contact
  - title: Legal
    url: /terms-and-conditions
  - title: Vinyls
    url: /vinyls
  - title: I ❤️ OPENSOURCE
    url: /i-love-opensource

socials:
  - title: Github
    url: "https://github.com/rafalmasiarek"
    icon: "fab fa-github"
# I need to take a temporary break from social media, account suspended.”
#  - title: Linkedin
#    url: "https://www.linkedin.com/in/rafal-masiarek/"
#    icon: "fab fa-linkedin-in"

compress_html:
  ignore:
    envs: [development, local]
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  startings: [html, head, body]

licenses:
  - name: Bootstrap
    version: 5.3.8
    license: MIT
    author: The Bootstrap Authors
    homepage: https://getbootstrap.com/
    source_url: https://github.com/twbs/bootstrap
    source: JS
  - name: instagram.css
    license: MIT
    author: "Yan Zhu (https://github.com/picturepan2)"
    source_url: https://github.com/picturepan2/instagram.css
    source: JS
  - name: js-fair-consent
    version: v1.0.0
    license: MIT
    author: Rafał Masiarek
    source_url: https://github.com/rafalmasiarek/js-fair-consent
    source: JS
  - name: js-form-prefill
    version: v1.2.0
    license: MIT
    author: Rafał Masiarek
    source_url: https://github.com/rafalmasiarek/js-form-prefill
    source: JS
  - name: Twemoji
    version: v14.0.2
    license: MIT
    author: Twitter
    homepage: https://twemoji.twitter.com/
    source_url: https://github.com/twitter/twemoji
    source: JS
  - name: PDF.js
    version: v3.11.174
    license: Apache-2.0
    author: Mozilla and PDF.js contributors
    homepage: https://mozilla.github.io/pdf.js/
    source_url: https://github.com/mozilla/pdf.js
    source: JS
  - name: OpenPGP.js
    version: v6.3.0
    license: LGPL-3.0-or-later
    author: OpenPGP.js contributors
    homepage: https://openpgpjs.org/
    source_url: https://github.com/openpgpjs/openpgpjs
    source: JS
    
include:
  - .htaccess
  - _config.yml
  - .well-known
  - projects
  - "projects/**/.*"

exclude:
  - "**/*.md.overwrite"
  - "projects/content"
  - "projects/storage"
  - "projects/media"
  - "projects/cache"
  - "projects/logs"
  - "projects/site/accounts"
  - "projects/site/sessions"
