title: "Rafal Masiarek"
url: "https://masiarek.pl"
baseurl: ""

description: "I am devops. Automation and configuration management tools are the foundation of my work"
github_repo: "https://github.com/rafalmasiarek/rafalmasiarek.github.io"

recaptcha_site_key: "6LfvSI4rAAAAABdOXvYNnDMZEzd_K57A94LlEghS"

# plugins
plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-assets

collections:
  vinyls:
    output: true
    permalink: /vinyls/:name/

nav:
  - title: Home
    url: /
  - title: Contact
    url: /contact
  - title: Legal
    url: /terms-and-conditions
  - title: Vinyls
    url: /vinyls
  - title: Projects
    url: /projects

socials:
  - title: Github
    url: "https://github.com/rafalmasiarek"
    icon: "fab fa-github"
  - title: Linkedin
    url: "https://www.linkedin.com/in/rafal-masiarek/"
    icon: "fab fa-linkedin-in"

compress_html:
  ignore:
    envs: [development, local]
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  startings: [html, head, body]

include:
  - sw-vinyls.js

exclude:
  - "**/*.md.overwrite"
